Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -1,11 +1,12 @@
 #!/bin/bash
-#====================================================
-#	SCRIPT: BOTSSH SSHPLUS MANAGER
-#	DESENVOLVIDO POR:	CRAZY_VPN
-#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
-#	CANAL TELEGRAM:	http://t.me/sshplus
-#====================================================
 clear
+#===================================================
+#   SCRIPT: BOTSSH SSHPLUS MANAGER
+#   FECHA ACT.: 24 de Ene 2021
+#   DESARROLLADO POR:	CRAZY_VPN
+#   CONTACTO TELEGRAM:	http://t.me/crazy_vpn
+#   CANAL TELEGRAM:	http://t.me/sshplus
+#====================================================
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@KIRITO_SSH" ]] && exit 0
 fun_bar() {
     comando[0]="$1"
@@ -38,10 +39,10 @@ fun_botOnOff() {
     [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
         clear
         echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-        echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "
+        echo -ne "\033[1;32mINFORME SU TOKEN:\033[1;37m "
         read tokenbot
         echo ""
-        echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "
+        echo -ne "\033[1;32mINFORME SU ID:\033[1;37m "
         read iduser
         clear
         echo -e "\033[1;32mINICIANDO BOT SSHPLUS \033[0m\n"
@@ -67,12 +68,12 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT SSHPLUS ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
+        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m ¡BOT SSHPLUS ACTIVADO!\033[0m" || echo -e "\n\033[1;31m ¡ERROR! REVISE SU INFORMACIÓN\033[0m"
         sleep 2
         menu
     } || {
         clear
-        echo -e "\033[1;32mPARANDO BOT SSHPLUS... \033[0m\n"
+        echo -e "\033[1;32mDETENIENDO BOT SSHPLUS... \033[0m\n"
         fun_bot2() {
             screen -r -S "bot_plus" -X quit
             screen -wipe 1>/dev/null 2>/dev/null
@@ -83,7 +84,7 @@ fun_botOnOff() {
             sleep 1
         }
         fun_bar 'fun_bot2'
-        echo -e "\n\033[1;32m \033[1;31mBOT SSHPLUS PARADO! \033[0m"
+        echo -e "\n\033[1;32m \033[1;31m¡BOT SSHPLUS DETENIDO! \033[0m"
         sleep 2
         menu
     }
@@ -91,20 +92,20 @@ fun_botOnOff() {
 
 fun_instbot() {
     echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE OS SEGUINTES BOT\033[1;37m:\033[0m"
-    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SSHPLUS_BOT \033[1;33mE PEGUE SEU ID \033[1;31mOPCAO: \033[1;37m/id\033[0m"
+    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCIÓN \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mDESDE SU TELEGRAM ACCEDA LOS SIGUIENTES BOTS\033[1;37m:\033[0m"
+    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREE SU BOT \033[1;31mOPCIÓN: \033[1;37m/newbot\033[0m"
+    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@SSHPLUS_BOT \033[1;33mY OBTENGA SU ID \033[1;31mOPCIÓN: \033[1;37m/id\033[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
     echo ""
-    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
-    [[ "$resposta" = 's' ]] && {
+    read -p "¿DESEA CONTINUAR ? [s/n]: " -e -i s respuesta
+    [[ "$respuesta" = 's' ]] && {
         fun_botOnOff
     } || {
-        echo -e "\n\033[1;31mRetornando...\033[0m"
+        echo -e "\n\033[1;31mRegresando...\033[0m"
         sleep 2
         menu
     }
 }
 [[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
-#fim
+#fin
